### PR TITLE
v1.0.6 ( Car / Train Node Mover )

### PR DESCRIPTION
**Pull request by Pxpe123**
Introduction of Train and Car Node Mover 
- Works for both base game and Modded train lines 
- Car Node mover allowing traffic  
Instructions:  
Car Nodes  
Export the node files required for relocation to another spot.  
Place The Exported .XML files in to the Files Folder ensuring that it is empty before starting 
Next Run Map mover as normal and wait for completion  
await the App to says its completed and reimport to game  

Train Nodes 
open Train.dat you want moving in openIV (so it turns into text) ctrl + T shortcut  
then press export as txt file Place it into ./Files  
Next Run Map mover as normal and wait for completion  
await the App to says its completed and reimport to game

### CODE REVIEW

**Comment by 92-Smallo** [comment]
I'll have a look at things in the next few days, busy with work. However I'd much rather read the files directly rather then having to read text files. I'll have a look at being able to achieve that as well.

**Comment by Pxpe123** [comment]
No problem its a pretty basic bit of code i added in "OtherFunctions" and as a message box question so its not forced
Also if you push this into main builds all i ask is a slither of credit and ill make more like this if i can think of other things alike

**Comment by Pxpe123** [comment]
> I'll have a look at things in the next few days, busy with work. However I'd much rather read the files directly rather then having to read text files. I'll have a look at being able to achieve that as well.

No problem its a pretty basic bit of code i added in "OtherFunctions" and as a message box question so its not forced
Also if you push this into main builds all i ask is a slither of credit and ill make more like this if i can think of other things alike

**Comment by 92-Smallo** [comment]
Alright, upon further investigation this method of moving vehicle nodes will break almost every single thing in them. You cannot simply just change the node positions, save things and move on. This will break links, node bounds, etc. So unfortunately I will not be merging this.

**Pull request closed without merging**
